name: Salesforce plugin CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build tool setup Stage
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Application build Stage
      run: |
           mvn clean install

    - name: Code Coverage Stage
      run: |
           mvn -e -X clean verify sonar:sonar \
             -Dsonar.projectKey=sander \
             -Dsonar.projectName='sander' \
             -Dsonar.host.url=http://hivemet.com:9000 \
             -Dsonar.token=${{ secrets.AWSPLUGIN_KEY }}
          

   
